### ISSUE TITLE
크롬 드라이버 라이선스 보증 부인

### ISSUE THREAD

**Issue by CwhiteKJ** [KafJS/ClassCardMacro#1]
크롬 드라이버 `BSD 3-Clause` 에 의거하여 배포 시 지켜야 할 의무사항이 있습니다.    
```
배포시 의무사항:

재배포시 저작권 표시, 준수 조건 및 보증부인에 대한 고지사항을 소스코드 또는 문서 및 기타 자료에 포함

최초개발자나 기여자의 이름을 제품에 대한 보증이나 홍보에 사용하지 못함
```

**보증부인에 대한 고지사항**을 따로 표기 해야할 듯 합니다.

**Comment by KafJS** [comment]
크롬 드라이버 라이센스 고지했습니다 !
고지 못한 점 죄송합니다 😭

**Comment by CwhiteKJ** [comment]
**저작권자와 기여자는 이 소스코드를 '있는 그대로' 제공하며 어떠한 보증도 하지않습니다.**    
이렇게 적으면 될 듯 한데요

**Comment by KafJS** [comment]
했습니다 :)
